version: "3"

networks:
  postgres:
    driver: bridge
  rabbit:
    driver: bridge

services:
  rotator:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
      args:
        - CONFIG_FILE_NAME=rotator_docker
    container_name: rotator
    environment:
      WAIT_HOSTS: postgres:5432, rabbit:5672
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - postgres
      - rabbit
    networks:
      - postgres
      - rabbit

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567890"
      POSTGRES_DB: "rotator"
    volumes:
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
    restart: always
    networks:
      - rabbit