name: Rotator tests

on:
  push:

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          working-directory: .